### ISSUE TITLE
Fix sharing buttons 

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#323]
Possibly just me but the sharing buttons no longer seem to do the right thing, for example Twitter just opens the compose tweet page on the Twitter app on iOS with no message. Also the og thumbnail seems broken.

I’m afk for a while so adding it here unless anyone is able to pick up otherwise will look at when I can

**Comment by andriyleu** [comment]
Gonna give it a go.

**Comment by coderwassananmol** [comment]
Trying it! :)

**Comment by tessus** [comment]
Well, the button does exactly what it is supposed to do. Have you tried it in your desktop browser?
(You also have to deactivate any AdBlocker with cosmetic filtering.)

However, there's a real problem with the Twitter and FB share buttons, since the hostname is hardcoded.

I have submitted #326 to fix this.

**Comment by tessus** [comment]
since commit 50e350ec17aeb759916f3099b295d8387597c588 the share buttons do not work anymore.

**Comment by jenkoian** [comment]
Think this is sorted now, thanks for your help everyone 👍

**Comment by tessus** [comment]
@jenkoian I think you missed a few things:
- commit 5d976badec0461eeda160e692f2eebdb9c689531 screwed up my change. now it does not work anymore.
- commit 5d976badec0461eeda160e692f2eebdb9c689531 is only a partial fix, because the FB share button still does not work - it's actually not a fix at all, but hardcodes the link which is supposed to be compiled by the twitter javascript, yet the javascript stopped working after 50e350ec17aeb759916f3099b295d8387597c588 - so did the fb js btw.

The only way to actually fix this is to revert 5d976badec0461eeda160e692f2eebdb9c689531 and fix https://github.com/jenkoian/hacktoberfest-checker/blob/master/views/layouts/main.hbs#L67-L95

**Comment by jenkoian** [comment]
@tessus I've made some commits to master, please review. For me everything works just fine on the main url, the heroku one I'm seeing some odd behaviour. Need to investigate but it's late here so going to have to pick this up tomorrow.

**Comment by tessus** [comment]
@jenkoian your changes broke the following code:

```
document.getElementById('twitter-share').setAttribute('data-url', window.location.href);
document.getElementById('fb-share').setAttribute('data-href', window.location.href);
```

which you seem to have removed. I think you didn't understand why that code was necessary for a certain case in a reverse proxy situation (accessing `http://example.com/subdir/?username=xxx` directly).

Hardcoding the link is only a workaround and does not fix the root cause. As I mentioned before your javascript stopped working. You should investigate why that is and not hardcoding the links. These links are supposed to be created by the javascript. Now imagine twitter or fb changes the API. Then it stops working. Not so, if you had left it as it was at commit 62537219e5cd35a20105647f8bbf573b8fc0471a

You can always send me an email, if you want to discuss this offline.

**Comment by andriyleu** [comment]
Why this has been closed? Should be done the way @tessus has said. @jenkoian

**Comment by jenkoian** [comment]
@tessus want to get this working for you, would you mind just clarifying a few things..

> Hardcoding the link is only a workaround and does not fix the root cause.

Can you link to where this is hardcoded? Currently the urls are populated by the hostname passed across from the node side.

> Now imagine twitter or fb changes the API. Then it stops working.

This is likely related to the above, so you mean hardcoding the facebook/twitter urls here?

> This basically means that commits 50e350e - adf1ebd are somehow the problem.

Presumably you mean somewhere within this commit range? 
https://github.com/jenkoian/hacktoberfest-checker/compare/50e350ec17aeb759916f3099b295d8387597c588...adf1ebd1d4a923e917eaec7ce86118006ddc23d6

**Comment by tessus** [comment]
I'll answer your questions this evening (in about 8h).

**Comment by tessus** [comment]
> Presumably you mean somewhere within this commit range?
50e350e...adf1ebd

Yes, all commits after 50e350ec17aeb759916f3099b295d8387597c588 (except 25ca0b4e7582411f261f449fffef79091b67c4c3) are trying to fix things that were broken by 50e350ec17aeb759916f3099b295d8387597c588.

> Can you link to where this is hardcoded? Currently the urls are populated by the hostname passed across from the node side.

Maybe the term hardcoded is a bit exaggerated, but close to it.

The working code used this javascript:

```js
<!-- Twitter -->
    <script>
        window.twttr = (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0],
                t = window.twttr || {};
            if (d.getElementById(id)) return t;
            js = d.createElement(s);
            js.id = id;
            js.src = "https://platform.twitter.com/widgets.js";
            fjs.parentNode.insertBefore(js, fjs);
            t._e = [];
            t.ready = function (f) {
                t._e.push(f);
            };
            return t;
        }(document, "script", "twitter-wjs"));
    </script>
    <!-- Facebook -->
    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
```

which used the following HTML

```html
<div class="pa1">
                <a class="twitter-share-button white no-underline f6" id="twitter-share"
                    href="https://twitter.com/share"
                    data-size="large"
                    data-text="My progress on hacktoberfest {{ prs.length }} / {{prAmount}}"
                    data-url="{{hostname}}/?username={{username}}"
                    data-hashtags="hacktoberfest, hacktoberfestchecker">
                    Tweet
                </a>
            </div>
            <div class="fb-share-button pa1" id="fb-share"
                data-href="{{hostname}}/?username={{username}}"
                data-layout="button"
                data-size="large">
                    <a class="fb-xfbml-parse-ignore" href="https://www.facebook.com/sharer/sharer.php">Share</a>
            </div>
```

to create the social media share links dynamically. After commit 50e350ec17aeb759916f3099b295d8387597c588 this stopped working. Therefore somebody took the link that was created by the javascript and coded this directly into the html code:

```
href="https://twitter.com/intent/tweet?text=My progress on hacktoberfest {{ prs.length }} / {{prAmount}}&url={{hostname}}/?username={{username}}&hashtags=hacktoberfest, hacktoberfestchecker"
```

This broke my code, which changed this part `data-url="{{hostname}}/?username={{username}}"` in case somebody was using a reverse proxy setup and used a direct link to a user (not the /me link!).
You can see what I mean when you go to https://hacktoberfestchecker.herokuapp.com/?username=tessus
Hover over the tweet button and you see that the `url` parameter shows: `url=/?username=tessus` instead of `url=https://hacktoberfestchecker.herokuapp.com/?username=tessus`.

I explained in https://github.com/jenkoian/hacktoberfest-checker/pull/310#discussion_r222473703 why I had to use the following code to make this work:

```js
    // if hostname is empty, use location to build the link
    // needed for reverse proxy setup
    if (document.getElementById('melink') != null && document.getElementById('melink').innerHTML == '/me') {
        var link = `${window.location.href.split('?')[0]}me`;
        document.getElementById('melink').innerHTML = link;
        document.getElementById('melink').href = link;
        document.getElementById('twitter-share').setAttribute('data-url', window.location.href);
        document.getElementById('fb-share').setAttribute('data-href', window.location.href);
    }
```

Maybe it might just be easier to create an ENV var like `EXTERNAL_URL` or `APP_URL` for reverse proxy setups. 
The nodejs application does not know the URL by which it is accessed. 
It could be accessed as:
`https://example.com`
`https://example.com/hacktoberfest/`
`https://example.com/apps/hfc/`
`https://example.com/subdir1/subdir2/subdir3`
But the nodejs application only sees `/`.
I solved this by using the referer to figure this out. However, there are situations where there is no referer (using a direct link to the user stats like `https://example.com/?username=XXX`), in which case I use the above javascript to get the correct hostname (and path).

I hope I was able to clarify the situation.

**Comment by jenkoian** [comment]
Thanks that explains a lot. Yeah I think we should store the app url as an env var, seems like it would solve a lot. Unfortunately, I'm really struggling for time at the moment, if you want to do a patch that'd be great, otherwise may be a few days if you can wait.

**Comment by tessus** [comment]
I can do the code for the env var, but I don't know how to fix the javascript code that broke with  50e350e.

The links should not be created like they currently are. I really think you should revert some of those commits: 5d976badec0461eeda160e692f2eebdb9c689531 and 5f0baf7956c3e7785f921ff7d152cdbc073cbc02.

**Comment by jenkoian** [comment]
Need to spend more time (which I don't have :() looking into it but when I looked at the docs it didn't seem like data attributes like that were supported anymore.

**Comment by tessus** [comment]
Curious, I looked at the twitter doc https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/parameter-reference1 and there's a section `HTML data-* example`...

**Comment by jenkoian** [comment]
ah it was https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview.html I was looking at, didn't get as far as the Guides section! Alright, will try and find some time to sort all this.
