### ISSUE TITLE
Review fontawesome usage

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#414]
We are bringing in the entire fontawesome css file when we only use 3 icons (twitter, facebook and question mark). Review this, can we use it a more efficient manner? Only using the css we need? Can we use purgecss here?

**Comment by MarnixBouhuis** [comment]
Isn't it nicer to use the font awesome react module?

Treeshaking will automatically eliminate all code/icons we don't need. This will also allow future changes to use any icon they like without having to worry about regenerating css.

The only difference this makes is that instead of rendering icons using a font, we will be rendering icons using JS+SVG's.

**Comment by jenkoian** [comment]
@MarnixBouhuis Sounds good to me!

**Comment by MarnixBouhuis** [comment]
Alright, I can work on this. Can you assign me?

**Comment by MarnixBouhuis** [comment]
Done! Font awesome loaded from CDN is 12.5KB (css) + 67.8KB (fa-solid woff2) + 67.8KB (fa-brands woff2) = 148.1KB
New bundle size is increased by only 11.3KB, so a 136.8KB total reduction in resource size.

I've also updated font-awesome to the latest version so some icons look a bit different.
