### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by jenkoian** [jenkoian/hacktoberfest-checker#440]
I noticed travis isn't firing on PRs and also needs updating to use prettier and stuff

https://github.com/jenkoian/hacktoberfest-checker/blob/master/.travis.yml

**Comment by NLSteveO** [comment]
I would like to help with this but i believe i would have to access your travis ci settings from the travis website? Please correct me if i'm wrong as there might be another way?

I don't know if you have an issue for this but i recommend using `npm ci` in place of `npm install` in your travis config file. The reason for this is `npm ci` will install the dependencies at the versions in your package-lock file which i noticed you do commit to your repo. This way you won't have a build fail because maybe since you last ran `npm install` a dependency has updated and has a breaking change. This of course would be similar to locking the versions of your dependencies by not using the `~` or `^`. Just an idea if it interests you, i can make the change for that too.

**Comment by jenkoian** [comment]
Sounds good, I don't believe I need to give you access to travis as a public repo

**Comment by NLSteveO** [comment]
Ok, so it looks like the travis build fired for my PR. I did do a few tests with travis on my fork of your repo so i'm not sure if me having travis set up allowed the build to fire on your repo or not but either way i fixed why many builds were failing(calling `npm run eslint` when it doesn't exist) and made my suggested change to `npm ci`.  Also runs prettier now.
